// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iwlfaziuixssxufedrbv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3bGZheml1aXhzc3h1ZmVkcmJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyMzA1NjgsImV4cCI6MjA2ODgwNjU2OH0.9p_IzS8VzsR7dshwa8vlPQHsuFIzIoRI35Sg-gRB4q8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});